name: test

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jekyll/builder:4.0
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        ls .
        pwd
        echo $HOME
        env
